config/routes.rb
KnowledgeBase::Application.routes.draw do
  devise_for :users
resources :knowledges
resources :languages
root :to =>'knowledges#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :knowledge_id, :language_id,:framework_id, :other_id,:server_id
  belongs_to :knowledge
  belongs_to :language
  belongs_to :framework
  belongs_to :other
  belongs_to :server
end

app/models/framework.rb
class Framework < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :categories
  has_many :resources, :as => :resourcable
end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
  attr_accessible :description, :name, :user_id
  belongs_to :user
  has_many :categories
  has_many :languages, :through => :categories
  has_many :resources, :as => :resourcable
  has_many :frameworks, :through => :categories
  has_many :servers, :through => :categories
  has_many :others, :through => :categories
end

app/models/language.rb
class Language < ActiveRecord::Base
 attr_accessible :description, :name
 has_many :resources
 has_many :categories
end

app/models/offline_resource.rb
class OfflineResource < ActiveRecord::Base
  attr_accessible :description, :name, :resource_id
 belongs_to :resource, :polymorphic => true
end

app/models/online_resource.rb
class OnlineResource < ActiveRecord::Base
  attr_accessible :description, :name, :url, :resource_id
  belongs_to :resource, :polymorphic => true
end

app/models/other.rb
class Other < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :categories
  has_many :resources, :as => :resourcable
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  # attr_accessible :title, :body
attr_accessible :resourcable_id, :resourcable_type
	belongs_to :resourcable, :polymorphic => true
has_many :online_resources
has_many :offline_resources

end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :categories
  has_many :resources, :as => :resourcable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,:timeoutable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :uname,:email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :knowledges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/knowledges_controller.rb
class KnowledgesController < ApplicationController
before_filter :authenticate_user!
  def index
   # @search = knowledge.search(params[:search])
   # @knowledges = @search.all

    #@q = knowledge.search(params[:q])
    @knowledges = Knowledge.all
    @categories =Knowledge.first.categories.where("name IS NOT  NULL").select("distinct name")
     @languages =Knowledge.first.languages.all.compact
     @frameworks =Knowledge.first.frameworks.all.compact
  end
  
  def show
    @knowledge = Knowledge.find(params[:id])
  end
  
  def new
    @knowledge = Knowledge.new
  end
  
  def create
    @knowledge = Knowledge.new(params[:knowledge])
    if @knowledge.save
      flash[:notice] = "Successfully created knowledge."
      redirect_to @knowledge
    else
      render :action => 'new'
    end
  end
  
  def edit
    @knowledge = Knowledge.find(params[:id])
  end
  
  def update
    @knowledge = Knowledge.find(params[:id])
    if @knowledge.update_attributes(params[:knowledge])
      flash[:notice] = "Successfully updated knowledge."
      redirect_to @knowledge
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @knowledge = Knowledge.find(params[:id])
    @knowledge.destroy
    flash[:notice] = "Successfully destroyed knowledge."
    redirect_to knowledges_url
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

before_filter :authenticate_user!
  def index
   # @search = language.search(params[:search])
   # @languages = @search.all

    #@q = language.search(params[:q])
    @languages = Language.all
   
  end
  
  def show
    @language = Language.find(params[:id])
  end
  
  def new
    @language = Language.new
  end
  
  def create
    @language = Language.new(params[:language])
    if @language.save
      flash[:notice] = "Successfully created language."
      redirect_to @language
    else
      render :action => 'new'
    end
  end
  
  def edit
    @language = Language.find(params[:id])
  end
  
  def update
    @language = Language.find(params[:id])
    if @language.update_attributes(params[:language])
      flash[:notice] = "Successfully updated language."
      redirect_to @language
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @language = Language.find(params[:id])
    @language.destroy
    flash[:notice] = "Successfully destroyed language."
    redirect_to languages_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class(type)
    {error: "alert-error", notice: "alert-success", alert: "alert-info"}[type]
  end
  
  def menu_active(controller_name)
    return "active" if controller.controller_path == controller_name

  end
  def bar_active(category_name)
   	return "active" if category_name == "languages"
	else
        return "active" if controller.controller_path == category_name
         
       
 
  end 
  
  
  def breadcrumb
    s = ""
    url = request.path.split('?')  #remove extra query string parameters
    levels = url[0].split('/') #break up url into different levels
    if levels.blank?
      s += "<li class='active'>Home</li>\n"
    else
      levels.each_with_index do |level, index|
        unless level.blank?
          if index == levels.size-1 || 
             (level == levels[levels.size-2] && levels[levels.size-1].to_i > 0)
            s += "<li class='active'>#{CGI::unescape(level).gsub(/_/, ' ').capitalize}</li>\n" unless level.to_i > 0
          else
              link = "/"
              i = 1
              while i <= index
                link += "#{levels[i]}/"
                i+=1
              end
              s += "<li><a href=\"#{link}\">#{level.gsub(/_/, ' ').capitalize}<span class='divider'>/</span></a></li>\n"
          end
        end
      end
    end
    s
  end


  def action_active(action_name)
    "active" if controller.action_name == action_name
  end
def row_size(fz)
  if fz.length > 10
  text = fz[0, 10] + "\n" + fz[10, fz.length]
  else
   text = fz
end
  return text
  
  end

def web_presence(link)
      
      url = link 
      unless url.blank?
        url = "http://" << url unless url.match(/^https?:\/\//)
        link_to(url,"#{url}",:target => "_blank")
      end
  end


 #Change date format in edit time
 def change_date_format_for_edit_page(date)
    new_date = date.strftime("%m/%d/%Y")
    puts new_date.inspect
    return new_date
  end
  def green_icon
           "fam-add"
 end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/knowledges_helper.rb
module KnowledgesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/knowledges/_form.html.erb
<%= form_for @knowledge do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Description %><br />
    <%= f.text_field :description %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/knowledges/_menu.html.erb
<ul class="nav nav-tabs">
<% @categories.each do |name| %>
  <li class="<%= bar_active(name.name.pluralize) %>">
    <%= link_to '#' do %>

        <i class="icon-list-alt"></i>

	<%= name.name.pluralize %>

    <% end %>
  </li>
  
     <% end %> 
</ul>

app/views/knowledges/_tree.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        

		<link href="bootstrap-tree/css/bootstrap-tree.css" rel="stylesheet">
		<style>

.sidebar-nav {
    padding: 9px 0;
}
		</style>
    
    </head>
    <body>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3">
                    <div class="well">
                      <ul class="tree">
<% @categories.each do |name|%>
                        <li>
                          <a href="#" role="branch" class="tree-toggle closed" data-toggle="branch" data-value="Bootstrap_Tree"><%= name.name %></a>
<% if name.name == "language" %>
                     <ul class="branch ">
<% @languages.each do |name|%>
     

                              <li><a href="#" role="leaf" id="nut"><%=name.name %></a></li>
<% end %>                           
                          </ul>
  </li>
<li>

<% elsif name.name == "framework" %>

                          <ul class="branch">
<% @frameworks.each do |name|%>
                              <li><a href="#" role="leaf" id="nut"><%=name.name %></a></li>
   <% end %>                          
                          </ul>

<% end %>
        </li>
                       <% end %>           
                      </ul>
                    </div><!--/.well -->
                  </div><!--/span-->
                  <div class="span9" id="mainContent">
                      <div class="row-fluid">
                          <div class="well span8" id="editorArea">
                              <h1>Bootstrap Tree</h1>
                              <p>This is a template is a basic example of Bootstrap Tree. <a href="http://twitter.github.com/bootstrap/index.html">Bootstrap</a> is an excellent front-end framework from the guys at Twitter. This simple component is an add on component for rendering a basic Tree with some HTML configuration.</p>
  							<p>Click a node, on the left, to see it in action.</p>
                              <!-- <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p> -->
                          </div>
                      </div>
                      <div class="span8" id="reporter"></div>
                  </div>
            </div>
        </div>


        <script src="bootstrap-tree/js/bootstrap-tree.js"></script>
        <script src="example.js"></script>
    </body>
</html>

app/views/knowledges/edit.html.erb
<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @knowledge %> |
  <%= link_to "View All", knowledges_path %>
</p>

app/views/knowledges/index.html.erb
                <p> Welcome User, <%= current_user.uname %>,

<%= render 'menu' %>
<%= render 'tree' %>

app/views/knowledges/new.html.erb
<%= render  'form' %>

<p><%= link_to "Back to List", knowledges_path %></p>

app/views/knowledges/show.html.erb
<p>
  <strong>Name:</strong>
  <%=  @knowledge.name %>
</p>
<p>
  <strong>Description:</strong>
  <%=  @knowledge.description %>
</p>


<p>
  <%= link_to "Edit", edit_knowledge_path(@knowledge) %> |
  <%= link_to "Destroy", @knowledge, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", knowledges_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knowledge Base</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<style>
ul.nav li.dropdown:hover ul.dropdown-menu{
    display: block;    
}

a.menu:after, .dropdown-toggle:after {
  content: none;
}

</style>
</head>
<body>
  <div data-dropdown="dropdown" class="navbar">
    <div class="navbar-inner">
      <div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">  
<span class="icon-bar"></span>  
<span class="icon-bar"></span>  
<span class="icon-bar"></span>  
</a>  
<a class="brand" href="#"><img src="/images/lo.png" width="111" height="15" alt="knowledgebase logo" /></a>
        <ul class="nav"> 
          <% if current_user %>
            <!-- User menu here -->
            <li class="<%= menu_active('home') %>"><%= link_to "Home", '#' %></li>
            <li class="<%= menu_active('knowledges') %> ">
	    <ul class="nav secondary-nav">
	    <li class="dropdown">
            <%= link_to "Knowledges", knowledges_path,:form_class => "dropdown-toggle"  %>
              <ul class="dropdown-menu">
                <li><a href="#">Secondary link</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Another link</a></li>
              </ul>
            </li>
          </ul>
     </li>   
            <li class="<%= menu_active('resources') %>"><%= link_to "Resources", '#' %></li>
            <li class="<%= menu_active('others') %>"><%= link_to "Others", '#' %></li>
            <li class="<%= menu_active('about Us') %>"><%= link_to "AboutUs", '#' %></li>
            
          <% end %>
          
        </ul>
        <ul class="nav pull-right">
          <% if current_user %>            
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.uname %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">           
                <li><%= link_to "Logout", destroy_user_session_url, :method => :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", new_user_session_url %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>  
  <div class="container">
    
    <div id="notifications">
    <% [:error, :notice, :alert].each do |type| %>
      <% if flash[type] %>
        <%= content_tag :div, class: "alert #{alert_class(type)}" do %>
        <a class="close" data-dismiss="alert">x</a>
        <%= flash[type] %>
        <% end %>
      <% end %>
    <% end %>
    </div>
    
    
    
    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/grid.html.erb
<body>
<div class="container">
<div class="row">
<div class="span12">
<h1>w3resource.com is a web design and development tutorial.</h1> 
</div>
</div>
<div class="row">
<div class="span2">
<p><img src="/images/logo.png" width="149" height="52" alt="w3resource logo" /></p> 
</div>
<div class="span10">
<p>w3resource offers web development tutorials. We believe in Open Source. Love standards. And prioritize simplicity and readability while serving content. With 3000+ unique content pages and thousands of examples, we are comprehensive. We have online practice editors to play around with the example codes.</p> 
</div>
</div>
<div class="row">
<div class="span12">
<h3>Some of the topics and more... :</h3> 
</div>
<div class="span2">
<p><img src="images/html5_logo.png" width="140" height="86" alt="html5 logo" /></p> 
</div>
<div class="span2">
<p><img src="images/javascript-logo.png" width="140" height="86" alt="javascript logo" /></p> 
</div>
<div class="span2">
<p><img src="images/json.gif" width="140" height="86" alt="JSON logo" /></p> 
</div>
<div class="span2">
<p><img src="images/php.png" width="140" height="86" alt="PHP logo" /></p> 
</div>
<div class="span2">
<p><img src="images/mysql-logo.png" width="140" height="86" alt="MySQL logo" /></p> 
</div>
<div class="span2">
<p><img src="images/browser-statistics.png" width="140" height="86" alt="Browser Statistics logo" /></p> 
</div>
</div>
<div class="row">
<div class="span12">
<h3>Social networking sites to share:</h3> 
</div>
</div>
<div class="row">
<div class="span1">
<p><img src="images/gplus.png" width="50" height="49" alt="GPlus logo" /></p> 
</div>
<div class="span1">
<p><img src="images/twitter.png" width="50" height="38" alt="Twitter logo" /></p> 
</div>
<div class="span1">
<p><img src="images/orkut.png" width="50" height="55" alt="Orkut logo" /></p> 
</div>
<div class="span1">
<p><img src="images/ipad.png" width="50" height="53" alt="iPad logo" /></p> 
</div>
<div class="span1">
<p><img src="images/digo.png" width="50" height="54" alt="Digo logo" /></p> 
</div>
<div class="span1">
<p><img src="images/zapface.png" width="51" height="53" alt="Zapface logo" /></p> 
</div>
<div class="span1">
<p><img src="images/facebook.png" width="48" height="53" alt="facebook logo" /></p> 
</div>
<div class="span1">
<p><img src="images/netvibes.png" width="51" height="53" alt="Netvibes logo" /></p> 
</div>
<div class="span1">
<p><img src="images/linkedin.png" width="49" height="54" alt="LinkedIn logo" /></p> 
</div>
<div class="span1">
<p><img src="images/newsvine.png" width="48" height="53" alt="Newsvine logo" /></p> 
</div>
<div class="span1">
<p><img src="images/blogger.png" width="51" height="53" alt="Blogger logo" /></p> 
</div>
<div class="span1">
<p><img src="images/reditt.png" width="48" height="57" alt="Reddit logo" /></p> 
</div>
</div>
<div class="row">
<div class="span3">
<h3>Fontend Development:</h3> 
<p>HTML4.0, XHTML1.0, CSS2.1, HTML5, CSS3, JavaScript</p>
</div>
<div class="span3">
<h3>Backend Developemt:</h3> 
<p>PHP, Ruby, Python, Java, ASP.NET, SCALA</p>
</div>
<div class="span3">
<h3>Database Management:</h3> 
<p>SQL, MySQL POstgreSQL, NoSQL, MongoDB</p>
</div>
<div class="span3">
<h3>APIs, Tools and Tips:</h3> 
<p>Google Plus API, Twitter Bootstrap, JSON, Firebug, WebPNG</p>
</div>
</div>
</div>

<div class="row"><br>
 <div class="span12">

        <%= yield %>
      </div>
 </div>
</body>

app/views/layouts/knowledge.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knowledge Base</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<style>
 body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
	  .nav li {
	  padding-top: 5px;
	  }
	  .leaderboard {
  padding: 60px;
  margin-bottom: 30px;
  background-image: url('images/gridbg.gif');
  background-repeat:repeat;
  -webkit-border-radius: 6px;
  -moz-border-radius: 6px;
  border-radius: 6px;
}
.leaderboard h1 {
  font-size: 40px;
  margin-bottom: 5px;
  line-height: 1;
  letter-spacing: -1px;
  color:#FF6600;
}
.leaderboard p {
  font-size: 18px;
  font-weight: 200;
  line-height: 27px;
}

</style>
</head>
<body>
<script>
$(document).ready(function(){
$(".test").click(function(){
$(".test").addClass("active");
alert("works")
})
alert("jh");
});
</script>
<div class="navbar navbar-fixed-top">  
<div class="navbar-inner">  
<div class="container">  
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">  
<span class="icon-bar"></span>  
<span class="icon-bar"></span>  
<span class="icon-bar"></span>  
</a>  
<a class="brand" href="#"><img src="/images/lo.png" width="111" height="15" alt="knowledgebase logo" /></a>  
<div class="nav-collapse">  
<ul class="nav"> 
<li class="active"><a href="#">Home</a></li>   
<li class=""><a href="#">Knowledges</a></li>  
<li class="test"><a href="#" >Resources</a></li>  
<li><a href="#">Graphs</a></li>

</ul> 
<ul class="nav pull-right"> 
<li class="dropdown">  
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span>   
</a> 
     <ul class="dropdown-menu">
              <li>  <%= link_to "Logout", "#" %></li>
	</ul>
	</li>
  </ul>   
</div><!--/.nav-collapse -->
</div>  
</div>  
</div>  
<div class="container">  
<!-- Main hero unit for a primary marketing message or call to action -->  
<div class="leaderboard">  
<h1>Here you can check your knowledge skills</h1>  
<p>It Contains various languages that you know and it provides various online and offline resources to improve knowledge.</p>  

</div>  
<!-- Example row of columns -->  
<div class="row">  
<div class="span4">  
<h2>Graphs</h2>  
<p>Varoius graphs provides you to check in which your are strong which knowledge has highly occupied in this tutorials. </p>  
<p><a class="btn btn-success btn-large" href="#">View apps</a></p>  
</div>  
<div class="span4">
<h2>Developer Guide</h2>  
<p> Most of the snippets included in this site are real world examples or you can easily get start with that . </p>  
<p><a class="btn btn-success btn-large" href="#">View apps</a></p>  
</div>  
<div class="span4">  
<h2>PHP MySQL Apps</h2>  
<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>  
<p><a class="btn btn-success btn-large" href="#">View apps</a></p>  
</div>  
</div>  
<div class="row"><br>
 <div class="span12">

        <%= yield %>
      </div>
 </div>

<hr>  
<footer>  
<p>santhu© Company 2012</p>  
</footer>  
</div> <!-- /container -->



  
</body>
</html>